### ISSUE TITLE
CSV problem

### ISSUE THREAD

**Issue by donieosullivan** [storyful/irish-elections#17]
I hope this email finds  you well. Just wanted to flag an error on the csv export of IEOD where the candidates party is left blank. Just wondering if you have a work around?

**Comment by giannileggio** [comment]
@donieosullivan I can't replicate the issue. Can you please tell me in which candidate you see the blank space?

**Comment by donieosullivan** [comment]
Hey Gianni,

This issue was resolved

On Tue, Feb 9, 2016 at 12:33 PM, Gianni Leggio <notifications@github.com>
wrote:

> @donieosullivan <https://github.com/donieosullivan> I can't replicate the
> issue. Can you please tell me in which candidate you see the blank space?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/storyful/irish-elections/issues/17#issuecomment-181972782>
> .
>



-- 
Donie O'Sullivan
Journalist | Storyful

+353 1 537 0296 tel
+353 87 133 2278 mobile
donie.osullivan@storyful.com
@donie <http://twitter.com/donie>

-- 
HQ - 76 Lower Baggot Street, Dublin 2, Ireland
NYC - 1185 Avenue of the Americas, 23rd Floor, New York, NY 10036, USA
Hong Kong - Level 25, Central Plaza, 18 Harbour Road, Wan Chai, Hong Kong 
SAR
Sydney - Level 4, 2 Holt Street, Surry Hills, NSW 2010, Australia



Storyful powers great storytelling 
<https://www.youtube.com/watch?v=zKOz574TLnU>

This e-mail and any attachments are confidential, may be legally privileged 
and are the property of Storyful Limited on whose systems they were 
generated. Storyful Limited is registered in Ireland under number 478477, 
has its registered office at Ferry House, 48 Lower Mount Street, Dublin 2, 
Ireland. If you have received this e-mail in error, please notify the 
sender immediately and do not use, distribute, store or copy it in any way. 
Statements or opinions in this e-mail or any attachment are those of the 
author and are not necessarily agreed or authorised by Storyful Limited. 
Storyful Limited may monitor outgoing or incoming emails as permitted by 
law. It accepts no liability for viruses introduced by this e-mail or 
attachments.

**Comment by giannileggio** [comment]
Cool, closing it
