### ISSUE TITLE
Candidate website links loop back to http://irish-elections.storyful.com/candidates/

### ISSUE THREAD

**Issue by peerside** [storyful/irish-elections#2]
Candidate website links loop back to http://irish-elections.storyful.com/candidates/
For example:
On the page for [ Catherine Ardagh]  (http://irish-elections.storyful.com/candidates/catherine-ardagh) you can click on her website URL 'w:http://www.catherineardagh.ie' and it directs to http://irish-elections.storyful.com/candidates/catherine-ardagh instead of http://www.catherineardagh.ie/

The candidate data seems fine in candidates.csv. i.e. 
"11/6/2015 11:12:21,Catherine,Ardagh,,Fianna Fáil,Dublin South Central,http://www.catherineardagh.ie/,https://www.fiannafail.ie/people/cllr-catherine-ardagh/,catherine@ardagh.org,,No,https://pbs.twimg.com/profile_images/450938486552403968/9DbKY90I.jpeg,https://www.facebook.com/ardaghforaction?_rdr=p,https://twitter.com/cardagh,https://www.linkedin.com/in/catherineardagh,,,,01 531 3300,,Female,http://www.catherineardagh.ie/,Yes,,,
"

**Comment by JonMidhir** [comment]
Thanks @peerside 

Error is here: https://github.com/storyful/irish-elections/blob/master/app/views/candidates/show.html.erb#L48

cc/ @giannileggio @shaicoleman

**Comment by peerside** [comment]
Ok - that has to be the quickest turnaround I've ever had to bug report :-) Thanks !

**Comment by JonMidhir** [comment]
Happy to help :)

Fixed in https://github.com/storyful/irish-elections/commit/9ad1efef07f2a091f791e906d31d727c0fdf4c76
