### ISSUE TITLE
Email addresses in JSON

### ISSUE THREAD

**Issue by donieosullivan** [storyful/irish-elections#25]
A user emails: 

Is there a reason why the candidates email is available in the csv download (http://irish-elections.storyful.com/candidates.csv) but not in the JSON (http://irish-elections.storyful.com/candidates.json)?

**Comment by giannileggio** [comment]
Fixed in https://github.com/storyful/irish-elections/commit/f57a84900c136bc8adf325eada428e05e2d2e339
