### ISSUE TITLE
Party names on Candidate/search result pages

### ISSUE THREAD

**Issue by donieosullivan** [storyful/irish-elections#3]
Excellent resource. Just one suggestion, when you pull up a constituency it would be good if you also showed the party on the screen rather than having to go into every candidate to see which party they are from.

**Comment by giannileggio** [comment]
Should it stay in pages like this: http://irish-elections.storyful.com/candidates
It could fit underneath the constituency

**Comment by donieosullivan** [comment]
Yep would be good - would make more sense if it is structured like:

Candidate name
Party
Constituency

That possible?  @giannileggio

**Comment by giannileggio** [comment]
Yes, this is possible @donieosullivan

**Comment by giannileggio** [comment]
Fixed in https://github.com/storyful/irish-elections/pull/10
