### ISSUE TITLE
API Documentation tab at the top of website

### ISSUE THREAD

**Issue by donieosullivan** [storyful/irish-elections#4]
Only "API" is hyperlinked, not the rest of the text

**Comment by giannileggio** [comment]
It works for me, I have this <a href="http://irish-elections.storyful.com/apipie">API Documentation</a>

@donieosullivan which browser are you using?

**Comment by JonMidhir** [comment]
It's broken for me in Chrome @giannileggio

**Comment by donieosullivan** [comment]
Chrome - still broken for me

On Thu, Nov 26, 2015 at 12:19 PM, John Hope <notifications@github.com>
wrote:

> It's broken for me in Chrome @giannileggio
> <https://github.com/giannileggio>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/storyful/irish-elections/issues/4#issuecomment-159899299>
> .
>



-- 
Donie O'Sullivan
Journalist | Storyful

+353 1 537 0296 tel
+353 87 133 2278 mobile
donie.osullivan@storyful.com
@donie <http://twitter.com/donie>

-- 
HQ - Ferry House, 48 Lower Mount Street, Dublin 2, Ireland
NYC - 1185 Avenue of the Americas, 23rd Floor, New York, NY 10036, USA
Hong Kong - Level 25, Central Plaza, 18 Harbour Road, Wan Chai, Hong Kong 
SAR
Sydney - Level 4, 2 Holt Street, Surry Hills, NSW 2010, Australia



Storyful powers great storytelling 
<https://www.youtube.com/watch?v=zKOz574TLnU>

This e-mail and any attachments are confidential, may be legally privileged 
and are the property of Storyful Limited on whose systems they were 
generated. Storyful Limited is registered in Ireland under number 478477, 
has its registered office at Ferry House, 48 Lower Mount Street, Dublin 2, 
Ireland. If you have received this e-mail in error, please notify the 
sender immediately and do not use, distribute, store or copy it in any way. 
Statements or opinions in this e-mail or any attachment are those of the 
author and are not necessarily agreed or authorised by Storyful Limited. 
Storyful Limited may monitor outgoing or incoming emails as permitted by 
law. It accepts no liability for viruses introduced by this e-mail or 
attachments.

**Comment by JonMidhir** [comment]
It's the 'fork me on github' ribbon blocking clicks.

**Comment by giannileggio** [comment]
Now I can replicate it, it happens on small resolutions. We could play a bit with z-index

**Comment by JonMidhir** [comment]
Fixed by https://github.com/storyful/irish-elections/pull/9.
